### ISSUE TITLE
Links in Contact tab 

### ISSUE THREAD

**Issue by harshraj22** [Surya1231/Surya1231.github.io#4]
Each link in contact me tab redirects to codechef profile ( though the icons are for various other profiles like linkedin, codeforces etc ) [portfolio](https://surya1231.github.io/)

![Screenshot from 2020-03-14 11-45-58](https://user-images.githubusercontent.com/46635452/76676437-8c120d00-65e9-11ea-87c6-f09696085c84.png)

**Comment by Surya1231** [comment]
Thank you for raising the issue. I have fixed the issue.
